<#
.SYNOPSIS
Copy generated sample scenes back from Assets/ into the package's Samples~ source.

.DESCRIPTION
Scenes in this project are generated by editor menu items, and the generators
write into the *imported* copy under `Assets/Samples/...`. That copy is
disposable: `Restore-LiteRtLmSamples.ps1 -Force` overwrites it from `Samples~`,
which silently deletes any scene that was only ever generated into Assets.

That is exactly how the TTS scene disappeared once. This script closes the loop:
generate in the editor, run this, and the scene becomes part of the package.

Only `.unity` (and their `.meta`) files are copied, and only where the package
already has a matching sample folder — so it can never invent files or clobber
source code.

.EXAMPLE
    .\Tools\Windows\Sync-LiteRtLmGeneratedScenes.ps1
.EXAMPLE
    .\Tools\Windows\Sync-LiteRtLmGeneratedScenes.ps1 -WhatIf
#>
[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [switch]$Prune
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$packageDir = Join-Path $repoRoot 'Packages/com.leuconoe.litert-lm-unity'
$packageJsonPath = Join-Path $packageDir 'package.json'
if (-not (Test-Path $packageJsonPath)) { throw "package.json not found at $packageJsonPath" }

$package = Get-Content $packageJsonPath -Raw | ConvertFrom-Json
$copied = 0
$skipped = 0

foreach ($sample in $package.samples) {
    $packageScenes = Join-Path (Join-Path $packageDir $sample.path) 'Scenes'
    $importedScenes = Join-Path $repoRoot (Join-Path 'Assets/Samples' (Join-Path $package.displayName (Join-Path $package.version (Join-Path $sample.displayName 'Scenes'))))

    if (-not (Test-Path $importedScenes)) {
        Write-Host "skip (not imported): $($sample.displayName)"
        continue
    }
    if (-not (Test-Path $packageScenes)) {
        New-Item -ItemType Directory -Force $packageScenes | Out-Null
    }

    foreach ($file in Get-ChildItem $importedScenes -File -Include *.unity, *.unity.meta -Recurse) {
        $relative = $file.FullName.Substring($importedScenes.Length).TrimStart('\', '/')
        # Generated/ holds throwaway per-build scenes; they are rebuilt on demand
        # and would only add churn to the package.
        if ($relative -like 'Generated*') { $skipped++; continue }

        $destination = Join-Path $packageScenes $relative
        $destinationParent = Split-Path -Parent $destination
        if (-not (Test-Path $destinationParent)) {
            New-Item -ItemType Directory -Force $destinationParent | Out-Null
        }

        $same = (Test-Path $destination) -and
                ((Get-FileHash $file.FullName).Hash -eq (Get-FileHash $destination).Hash)
        if ($same) { continue }

        if ($PSCmdlet.ShouldProcess($destination, 'copy generated scene')) {
            Copy-Item $file.FullName $destination -Force
            Write-Host ("copied  {0}/{1}" -f $sample.displayName, $relative)
            $copied++
        }
    }

    if ($Prune) {
        foreach ($file in Get-ChildItem $packageScenes -File -Include *.unity, *.unity.meta -Recurse) {
            $relative = $file.FullName.Substring($packageScenes.Length).TrimStart('\', '/')
            if (Test-Path (Join-Path $importedScenes $relative)) { continue }
            if ($PSCmdlet.ShouldProcess($file.FullName, 'remove scene absent from Assets')) {
                Remove-Item $file.FullName -Force
                Write-Host ("pruned  {0}/{1}" -f $sample.displayName, $relative)
            }
        }
    }
}

Write-Host ""
Write-Host "$copied scene file(s) synced into Samples~ ($skipped generated file(s) ignored)."
Write-Host "Commit these so the scenes survive Restore-LiteRtLmSamples.ps1 -Force."
